### ISSUE TITLE
Create Application If It Doesn't Exist

### ISSUE THREAD

**Issue by echohack** [echohack/lantern#8]
Currently if an application does not exist Lantern will simply throw an error as so:

```
Traceback (most recent call last):
  File "integration.py", line 28, in <module>
    v = lantern.API(username, password, app_name, build_name)
  File "/Users/echohack/code/lantern/lantern/lantern.py", line 246, in __init__
    self.set_app_id(app_name)
  File "/Users/echohack/code/lantern/lantern/lantern.py", line 252, in set_app_id
    app_search_xpath = ".//{0}app[@app_name='{1}']".format(self.get_xml_namespace(app_list_xml), app_name)
  File "/Users/echohack/code/lantern/lantern/lantern.py", line 358, in get_xml_namespace
    root = ET.fromstring(xml)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 16, column 0
```

First of all, this is probably a terrible error and doesn't inform the user of anything. But more importantly, the application should be created automatically by Lantern.

This is actually a pretty interesting problem, and there's a good reason why this feature doesn't already exist: If I remember correctly, Veracode does billing and contracts based on how many applications you have, and there doesn't appear to be an easy way to delete applications if you accidentally create one. So creating an app by accident is a problem.

This feature should include several things:

- A way to automatically create application profiles using the `createapp.do` api automatically if it doesn't exist.
- Exception handling if something horrible happens and the application profile can't be created, already exists, or generally fails.
- Research into how (generally speaking) Veracode does billing --- more than likely this is based off the number of applications you have + the size of the binaries you are scanning.
- Is there an option to delete application profiles? If not, understand exactly why.
- There might be a need to build some extra safety into creating an application if there's not an easy way to delete an application profile and if Veracode does billing based on this.

**Comment by ctcampbell** [comment]
Creating an app profile won't by itself cause any billing issues, and you could delete the app profile, if you haven't run a scan within that app profile, with no impact on license utilisation. Our Jenkins plugin has a tick box to automatically create an app profile if one doesn't exist so providing similar functionality in Lantern would be ok.
